name = "memos-worker"
compatibility_date = "2025-08-19"
main = "src/index.js"
[assets]
directory = "./src/public"
run_worker_first = [
	"/api/*"
]

[[d1_databases]]
binding = "DB"
database_id = "97922a40-27ef-4ad5-96de-fab8dadbdd2e"
database_name = "notes-db"

[[kv_namespaces]]
binding = "NOTES_KV"
id = "a836e3af0694407eb37e488cc63ab756"
preview_id = ""

[[r2_buckets]]
binding = "NOTES_R2_BUCKET"
bucket_name = "notes-r2-bucket"
preview_bucket_name = "notes-files-preview"
